displayName=Trawling Plus
author=Jin-Jiyunsun
description=Suite of trackers, guides and displays to help with deep sea trawling
tags=sailing,trawling,shoal,fishing,route,nets,boat,bluefin,halibut,marlin
version=1.2.5
plugins=com.trawlingplus.TrawlingPlusPlugin
build=standard
