package com.seteffects;

import java.util.HashSet;
import java.util.Set;
import net.runelite.api.Item;
import net.runelite.api.ItemContainer;
import net.runelite.api.gameval.ItemID;

/**
 * Warm clothing for the Wintertodt: four worn pieces give the maximum damage reduction there
 * (more add nothing) and each adds 1% Warmth regeneration. Any equipment slot counts, so this is
 * one tally across everything worn rather than a set. Matched on the raw item id, not the
 * variation-mapped one: some chains mix warm and non-warm items (the Volcanic abyssal whip shares
 * the abyssal whip's chain, the infernal tools share the Trailblazer tools'). The ids are the ones
 * the wiki's Warmth page lists (all slots, in its order); Slayer helmets are matched through
 * {@link SlayerHelm} since they come in dozens of recolours.
 */
final class WarmClothing
{
	static final int MAX_COUNTED = 4;

	private static final Set<Integer> WARM_IDS = new HashSet<>();

	static
	{
		int[] ids = {
			// Head
			ItemID.SANTA_MASK, ItemID.ANTISANTA_MASK, ItemID.EASTER19_BUNNY_MASK, ItemID.HUNTING_HAT_JAGUAR,
			ItemID.HUNTING_HAT_LEOPARD, ItemID.HUNTING_HAT_TIGER, ItemID.EASTER07_CHICKEN_HEAD, ItemID.EVIL_CHICKEN_HEAD,
			ItemID.PYROMANCER_HOOD, ItemID.SANTA_HAT, ItemID.BLACK_SANTA_HAT, ItemID.INVERTED_SANTA_HAT,
			ItemID.XM21_FESTIVE_HAT, ItemID.XMAS22_SANTA_CROWN, ItemID.MDAUGHTER_BEAR_HELMET, ItemID.TIARA_FIRE,
			ItemID.TIARA_ELEMENTAL, ItemID.RAMBLE_LUMBERJACK_HAT, ItemID.FORESTRY_LUMBERJACK_HAT, ItemID.XMAS22_GOGGLES,
			ItemID.XMAS23_HELMET, ItemID.SKILLCAPE_FIREMAKING_HOOD, ItemID.SKILLCAPE_MAX_HOOD_FIRECAPE, ItemID.SKILLCAPE_MAX_HOOD_INFERNALCAPE,
			ItemID.ZEP_BOMBER_CAP, ItemID.ZEP_BOMBER_CAP_GOGGLES, ItemID.WIN05_HAT1, ItemID.SLAYER_EARMUFFS,
			ItemID.WOLF_MASK, ItemID.WIN05_HAT4, ItemID.WIN05_HAT2, ItemID.WIN05_HAT3,
			// Neck
			ItemID.WIN05_SCARF2, ItemID.WIN05_SCARF3, ItemID.WIN05_SCARF4, ItemID.WIN05_SCARF1,
			ItemID.ALUFT_GNOME_SCARF, ItemID.PRIDE17_SCARF, ItemID.PRIDE23_SCARF_BISEXUAL, ItemID.PRIDE23_SCARF_ASEXUAL,
			ItemID.PRIDE23_SCARF_TRANSGENDER, ItemID.PRIDE23_SCARF_PANSEXUAL, ItemID.PRIDE23_SCARF_NONBINARY, ItemID.PRIDE23_SCARF_GENDERQUEER,
			ItemID.PRIDE23_SCARF_LESBIAN, ItemID.PRIDE23_SCARF_GAY, ItemID.XMAS24_FESTIVE_SCARF,
			// Hands
			ItemID.SANTA_GLOVES, ItemID.ANTISANTA_GLOVES, ItemID.EASTER16_ONSIE_GLOVES, ItemID.CLUE_HUNTER_GLOVES,
			ItemID.HUNTING_SILENT_GLOVES, ItemID.VIKINGGLOVES, ItemID.PYROMANCER_GLOVES, ItemID.WOLFENGLOVES_GREY,
			ItemID.WOLFENGLOVES_CRIMSON, ItemID.WOLFENGLOVES_TANGERINE, ItemID.WOLFENGLOVES_OCEAN, ItemID.WOLFENGLOVES_PURPLE,
			// Cape
			ItemID.SKILLCAPE_FIREMAKING, ItemID.SKILLCAPE_FIREMAKING_TRIMMED, ItemID.SKILLCAPE_MAX, ItemID.SKILLCAPE_MAX_WORN,
			ItemID.TZHAAR_CAPE_FIRE, ItemID.TZHAAR_CAPE_FIRE_BROKEN, ItemID.TZHAAR_CAPE_FIRE_TROUVER, ItemID.SKILLCAPE_MAX_FIRECAPE,
			ItemID.SKILLCAPE_MAX_FIRECAPE_BROKEN, ItemID.SKILLCAPE_MAX_FIRECAPE_TROUVER, ItemID.INFERNAL_CAPE_BROKEN, ItemID.INFERNAL_CAPE,
			ItemID.INFERNAL_CAPE_TROUVER, ItemID.INFERNAL_CAPE_TROUVER_BROKEN, ItemID.INFERNAL_CAPE_TROUVER_MANGLED, ItemID.SKILLCAPE_MAX_INFERNALCAPE,
			ItemID.SKILLCAPE_MAX_INFERNALCAPE_BROKEN, ItemID.SKILLCAPE_MAX_INFERNALCAPE_TROUVER, ItemID.SKILLCAPE_MAX_INFERNALCAPE_TROUVER_BROKEN, ItemID.SKILLCAPE_MAX_INFERNALCAPE_TROUVER_MANGLED,
			ItemID.TZHAAR_CAPE_OBSIDIAN, ItemID.SKILLCAPE_MAX_ANMA, ItemID.SKILLCAPE_MAX_ARDY, ItemID.SKILLCAPE_MAX_ASSEMBLER,
			ItemID.SKILLCAPE_MAX_ASSEMBLER_BROKEN, ItemID.SKILLCAPE_MAX_ASSEMBLER_TROUVER, ItemID.SKILLCAPE_MAX_MYTHICAL, ItemID.SKILLCAPE_MAX_GUTHIX2,
			ItemID.SKILLCAPE_MAX_GUTHIX2_TROUVER, ItemID.SKILLCAPE_MAX_GUTHIX2_BROKEN, ItemID.SKILLCAPE_MAX_SARADOMIN2, ItemID.SKILLCAPE_MAX_SARADOMIN2_TROUVER,
			ItemID.SKILLCAPE_MAX_SARADOMIN2_BROKEN, ItemID.SKILLCAPE_MAX_ZAMORAK2, ItemID.SKILLCAPE_MAX_ZAMORAK2_TROUVER, ItemID.SKILLCAPE_MAX_ZAMORAK2_BROKEN,
			ItemID.SKILLCAPE_MAX_GUTHIX, ItemID.SKILLCAPE_MAX_SARADOMIN, ItemID.SKILLCAPE_MAX_ZAMORAK, ItemID.WOLF_CLOAK,
			ItemID.PRIDE24_CAPE, ItemID.PRIDE24_CAPE_BISEXUAL, ItemID.PRIDE24_CAPE_ASEXUAL, ItemID.PRIDE24_CAPE_TRANSGENDER,
			ItemID.PRIDE24_CAPE_PANSEXUAL, ItemID.PRIDE24_CAPE_NONBINARY, ItemID.PRIDE24_CAPE_GENDERQUEER, ItemID.PRIDE24_CAPE_LESBIAN,
			ItemID.PRIDE24_CAPE_GAY, ItemID.CLUE_HUNTER_CLOAK, ItemID.TZHAAR_CAPE_OBSIDIAN_R,
			// Weapon
			ItemID.STAFF_OF_FIRE, ItemID.FIRE_BATTLESTAFF, ItemID.LAVA_BATTLESTAFF, ItemID.STEAM_BATTLESTAFF,
			ItemID.SMOKE_BATTLESTAFF, ItemID.MYSTIC_FIRE_STAFF, ItemID.MYSTIC_LAVA_STAFF, ItemID.MYSTIC_STEAM_BATTLESTAFF,
			ItemID.MYSTIC_SMOKE_BATTLESTAFF, ItemID.TWINFLAME_STAFF, ItemID.INFERNAL_AXE, ItemID.INFERNAL_AXE_EMPTY,
			ItemID.INFERNAL_PICKAXE, ItemID.INFERNAL_PICKAXE_EMPTY, ItemID.INFERNAL_HARPOON, ItemID.INFERNAL_HARPOON_EMPTY,
			ItemID.ABYSSAL_WHIP_LAVA, ItemID.ALE_GODS, ItemID.WINT_TORCH, ItemID.OSB10_DRAGON_CANDLE,
			// Shield
			ItemID.TOME_OF_FIRE, ItemID.TOME_OF_FIRE_UNCHARGED, ItemID.WINT_TORCH_OFFHAND, ItemID.SLAYER_BUGLAN_ON,
			// Body
			ItemID.SANTA_JACKET, ItemID.ANTISANTA_JACKET, ItemID.EASTER16_ONSIE_TOP, ItemID.CLUE_HUNTER_GARB,
			ItemID.HUNTING_CAMOFLAUGE_ROBE_POLAR, ItemID.HUNTING_CAMOFLAUGE_ROBE_POLAR_WORN, ItemID.HUNTING_CAMOFLAUGE_ROBE_WOOD, ItemID.HUNTING_CAMOFLAUGE_ROBE_WOOD_WORN,
			ItemID.HUNTING_CAMOFLAUGE_ROBE_JUNGLE, ItemID.HUNTING_CAMOFLAUGE_ROBE_JUNGLE_WORN, ItemID.HUNTING_CAMOFLAUGE_ROBE_DESERT, ItemID.HUNTING_CAMOFLAUGE_ROBE_DESERT_WORN,
			ItemID.HUNTING_TORSO_JAGUAR, ItemID.HUNTING_TORSO_LEOPARD, ItemID.HUNTING_TORSO_TIGER, ItemID.ZEP_BOMBER_JACKET,
			ItemID.YAK_HIDE_ARMOUR_BODY, ItemID.PYROMANCER_TOP, ItemID.EASTER07_CHICKEN_WINGS, ItemID.EVIL_CHICKEN_WINGS,
			ItemID.HW21_UGLY_JUMPER01, ItemID.HW21_UGLY_JUMPER02, ItemID.XMAS22_JUMPER, ItemID.OSB10_JUMPER_RED,
			ItemID.OSB10_JUMPER_YELLOW, ItemID.OSB10_JUMPER_BLUE, ItemID.OSB10_JUMPER_PURPLE, ItemID.OSB10_JUMPER_GREEN,
			ItemID.OSB10_JUMPER_WHITE, ItemID.PRIDE23_JUMPER, ItemID.PRIDE23_JUMPER_BISEXUAL, ItemID.PRIDE23_JUMPER_ASEXUAL,
			ItemID.PRIDE23_JUMPER_TRANSGENDER, ItemID.PRIDE23_JUMPER_PANSEXUAL, ItemID.PRIDE23_JUMPER_NONBINARY, ItemID.PRIDE23_JUMPER_GENDERQUEER,
			ItemID.PRIDE23_JUMPER_LESBIAN, ItemID.PRIDE23_JUMPER_GAY, ItemID.XMAS23_JUMPER,
			// Legs
			ItemID.SANTA_PANTS, ItemID.ANTISANTA_PANTS, ItemID.EASTER16_ONSIE_BOTTOM, ItemID.CLUE_HUNTER_TROUSERS,
			ItemID.HUNTING_TROUSERS_POLAR, ItemID.HUNTING_TROUSERS_POLAR_WORN, ItemID.HUNTING_TROUSERS_WOOD, ItemID.HUNTING_TROUSERS_WOOD_WORN,
			ItemID.HUNTING_TROUSERS_JUNGLE, ItemID.HUNTING_TROUSERS_JUNGLE_WORN, ItemID.HUNTING_TROUSERS_DESERT, ItemID.HUNTING_TROUSERS_DESERT_WORN,
			ItemID.HUNTING_TROUSERS_JAGUAR, ItemID.HUNTING_TROUSERS_LEOPARD, ItemID.HUNTING_TROUSERS_TIGER, ItemID.YAK_HIDE_ARMOUR_GREAVES,
			ItemID.EASTER07_CHICKEN_LEGS, ItemID.EVIL_CHICKEN_LEGS, ItemID.PYROMANCER_BOTTOM,
			// Ring
			ItemID.RING_OF_ELEMENTS, ItemID.RING_OF_ELEMENTS_CHARGED,
			// Feet
			ItemID.SANTA_BOOTS, ItemID.ANTISANTA_BOOTS, ItemID.BUNNYFEET, ItemID.CLUE_HUNTER_BOOTS,
			ItemID.PYROMANCER_BOOTS, ItemID.EASTER07_CHICKEN_FEET, ItemID.EVIL_CHICKEN_FEET, ItemID.XM21_FESTIVE_SLIPPERS,
			ItemID.MOLE_SLIPPERS, ItemID.HOLY_MOLEYS, ItemID.BEAR_SLIPPERS, ItemID.DEMON_SLIPPERS,
			ItemID.FROG_SLIPPERS, ItemID.OSB10_BOB_SLIPPERS, ItemID.OSB10_JAD_SLIPPERS, ItemID.COW_SLIPPERS,
			ItemID.COW_SLIPPERS_RECOL_1, ItemID.COW_SLIPPERS_RECOL_2, ItemID.COW_SLIPPERS_RECOL_3, ItemID.COW_SLIPPERS_RECOL_4
		};
		for (int id : ids)
		{
			WARM_IDS.add(id);
		}
	}

	private WarmClothing()
	{
	}

	static boolean isWarm(int rawItemId)
	{
		return WARM_IDS.contains(rawItemId) || SlayerHelm.isSlayerHelm(rawItemId);
	}

	static int count(ItemContainer equipment)
	{
		int count = 0;
		for (Item item : equipment.getItems())
		{
			if (item != null && item.getId() > 0 && isWarm(item.getId()))
			{
				count++;
			}
		}
		return count;
	}

	static EffectLine describe(ItemContainer equipment)
	{
		int count = count(equipment);
		String text;
		if (count >= MAX_COUNTED)
		{
			text = "You have a full set! Nice and toasty!";
		}
		else
		{
			text = "You have " + count + (count == 1 ? " piece" : " pieces") + " of warm clothing equipped.";
		}
		return new EffectLine("Warm clothing", Math.min(count, MAX_COUNTED), MAX_COUNTED, text);
	}
}
